config/routes.rb
NewspaperSubscriptions::Application.routes.draw do
  resources :newspapers do
    resources :subscription_plans, except: [:index, :show]
  end
  resources :users
  resource :sessions, only: [:new, :create, :destroy]
  resources :subscriptions, only: [:new, :create, :destroy]
  root to: "sessions#new"

end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
  attr_accessible :editor, :title, :subscription_plans_attributes

  belongs_to :user, foreign_key: :editor
  has_many :subscription_plans, dependent: :destroy, inverse_of: :newspaper
  accepts_nested_attributes_for :subscription_plans, reject_if: :all_blank

  validates :title, presence: true, uniqueness: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :user_id, :subscription_plan_id

  belongs_to :user
  belongs_to :subscription_plan
end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
  attr_accessible :is_weekly, :newspaper_id, :price

  belongs_to :newspaper
  validate :newspaper
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :price, presence: true
  validates_inclusion_of :is_weekly, :in => [true, false]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :subscription_plan_ids
  has_secure_password

  has_many :newspapers, foreign_key: :editor
  has_many :subscriptions, dependent: :destroy
  has_many :subscription_plans, through: :subscriptions

  validates :name, presence: true, uniqueness: true
  validates :password, presence: :true, length: {minimum: 6}, on: :create
  validates :password, confirmation: true, allow_nil: true
  validates :password_confirmation, presence: true, length: {minimum: 6}, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  def authenticate
    session[:token] ||= SecureRandom.urlsafe_base64
    @current_user = User.find_by_token(session[:token])
    unless @current_user
      redirect_to root_url
    end
  end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  def index
    @newspapers = Newspaper.all
  end

  def new
    @newspaper = Newspaper.new
  end

  def create
    @newspaper = Newspaper.new(params[:newspaper])
    @newspaper.subscription_plans.each do |sp|
      sp.newspaper_id = @newspaper.id
    end
    if @newspaper.save
      redirect_to newspaper_url(@newspaper)
    else
      p @newspaper.errors.full_messages
      flash[:notices] = "Could not create newspaper"
      render :new
    end
  end

  def show
    @newspaper = Newspaper.find(params[:id])
  end

  def edit
    @newspaper = Newspaper.find(params[:id])
    if @newspaper.user != @current_user
      redirect_to newspaper_url(@newspaper)
    end
  end

  def update
    @newspaper = Newspaper.find(params[:id])
    if @newspaper.update_attributes(params[:newspaper])
      redirect_to newspaper_url(@newspaper)
    else
      flash[:notices] = "Could not update newspaper"
      render :edit
    end
  end

  def destroy
    @newspaper = Newspaper.find(params[:id])
    @newspaper.destroy
    redirect_to newspapers_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticate, except: [:new, :create]

  def create
    user = User.find_by_name(params[:session][:name])
    if user
      if user.authenticate(params[:session][:password])
        user.token = SecureRandom.urlsafe_base64
        user.save
        session[:token] = user.token
        redirect_to user_url(user)
      else
        flash[:notices] = "Incorrect password"
        render :new
      end
    else
      flash[:notices] = "Incorrect username"
      render :new
    end
  end

  def destroy
    @current_user = nil
    session[:token] = nil
    render :new
  end
end

app/controllers/subscription_plans_controller.rb
class SubscriptionPlansController < ApplicationController
  def new
    @subscription_plan = SubscriptionPlan.new
  end

  def create
    @subscription_plan = SubscriptionPlan.new(params[:subscription_plan])
    @subscription_plan.newspaper_id = params[:newspaper_id]
    if @subscription_plan.save
      redirect_to newspaper_url(@subscription_plan.newspaper)
    else
      flash[:notices] = "Could not create subscription plan"
      render :new
    end
  end

  def edit
    @subscription_plan = SubscriptionPlan.find(params[:id])
    @np = @subscription_plan.newspaper
  end

  def update
    @subscription_plan = SubscriptionPlan.find(params[:id])
    if @subscription_plan.update_attributes(params[:subscription_plan])
      redirect_to newspaper_url(@subscription_plan.newspaper)
    else
      flash[:notices] = "Could not update subscription plan"
      render :edit
    end
  end

  def destroy
    @subscription_plan = SubscriptionPlan.find(params[:id])
    @subscription_plan.destroy
    redirect_to :back
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(params[:subscription])
    @subscription.user_id = @current_user.id
    if @subscription.save
      redirect_to :back
    else
      flash[:notices] = "Could not subscribe"
      redirect_to :back
    end
  end

  def destroy
    subscription = Subscription.find_by_subscription_plan_id(params[:id])
    subscription.destroy
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, except: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @newspapers = Newspaper.all
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @user.token = SecureRandom.urlsafe_base64
      @user.save
      session[:token] = @user.token
      redirect_to user_url(@user)
    else
      flash[:notices] = "Could not create user"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_url(@user)
    else
      flash[:notices] = "Could not create user"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewspaperSubscriptions</title>
  <%= csrf_meta_tags %>
</head>
<body>
<%= "Logged in as: #{@current_user.name}" if @current_user %>
<br>
<%= link_to "Profile", user_url(@current_user) if @current_user %>
<br>
<br>
<% if flash[:notices] %>
  <%= flash[:notices] %>
  <% flash[:notices] = nil %>
<% end %>

<%= yield %>

<br>
<%= link_to "All newspapers", newspapers_url if @current_user %>
<br>
<%= link_to "Create newspaper", new_newspaper_url if @current_user %>
<br>
<br>
<%= button_to "Sign out", sessions_url, method: :delete if @current_user %>
</body>
</html>

app/views/newspapers/edit.html.erb
<h1>Edit Newspaper</h1>

<form action="<%= newspaper_url(@newspaper) %>" method="post">
  <label for="newspaper_name">Name</label>
  <input type="text" name="newspaper[name]" id="newspaper_name" value="<%= @newspaper.name %>">
  <br>
  <label for="newspaper_editor">Editor</label>
  <select name="newspaper[editor]" id="newspaper_editor">
    <% User.all.each do |user| %>
      <option value="<%= user.id %>" <%= "selected" if np.editor == user.id %>><%= user.name %></option>
    <% end %>
  </select>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="put">

  <input type="submit" value="Update">
</form>

app/views/newspapers/index.html.erb
<h1>All Newspapers</h1>

<ul>
  <% @newspapers.each do |np| %>
    <li>
      <%= link_to np.title, newspaper_url(np) %>, Editor: <%= link_to np.user.name, user_url(np.user) %>
      <ul>
        <% np.subscription_plans.each do |sp| %>
          <li><%= "#{sp.price}, #{sp.is_weekly ? 'Weekly' : 'Daily'}" %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>
<br>

app/views/newspapers/new.html.erb
<h1>New Newspaper</h1>

<form action="<%= newspapers_url %>" method="post">
  <label for="newspaper_title">Name</label>
  <input type="text" name="newspaper[title]" id="newspaper_title" value="<%= @newspaper.title %>">
  <br>
  <label for="newspaper_editor">Editor</label>
  <select name="newspaper[editor]" id="newspaper_editor">
    <% User.all.each do |user| %>
      <option value="<%= user.id %>" <%= "selected" if @newspaper.editor == user.id %>><%= user.name %></option>
    <% end %>
  </select>
  <br>
  <br>
  Subscription plans:
  <br>
  <% 3.times do |i| %>
    <label for="newspaper_subscription_plan_<%= i %>_price">Price</label>
    <input type="text" placeholder="0.00" name="newspaper[subscription_plans_attributes][<%= i %>][price]" id="newspaper_subscription_plan_<%= i %>_price">
    <br>
    Type:
    <br>
    <input type="checkbox" name="newspaper[subscription_plans_attributes][<%= i %>][is_weekly]" value="<%= true %>" id="newspaper_subscription_<%= i %>_weekly">
    <label for="newspaper_subscription_<%= i %>_weekly">Weekly</label>
    <input type="checkbox" name="newspaper[subscription_plans_attributes][<%= i %>][is_weekly]" value="<%= false %>" id="newspaper_subscription_<%= i %>_daily">
    <label for="newspaper_subscription_<%= i %>_daily">Daily</label>
    <br>
    <br>
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <br>
  <input type="submit" value="Create">
</form>

app/views/newspapers/show.html.erb
<h1><%= @newspaper.title %></h1>

<h3>Edited by: <%= @newspaper.user.name %></h3>

<h4>Subscription plans:</h4>
<% @newspaper.subscription_plans.each do |sp| %>
  Price: $<%= sp.price %>
  <br>
  Type: <%= sp.is_weekly ? "Weekly" : "Daily" %>
  <% if @current_user.subscription_plans.include?(sp) %>
    <%= button_to "Unsubscribe", subscription_url(sp), method: :delete %>
  <% else %>
    <form action="<%= subscriptions_url %>" method="post">
      <input type="hidden" name="subscription[subscription_plan_id]" value="<%= sp.id %>">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="Subscribe">
    </form>
  <% end %>
  <% if @newspaper.user == @current_user %>
    <%= button_to "Edit", edit_newspaper_subscription_plan_url(@newspaper.id), method: :get %>
    <%= button_to "Delete", newspaper_subscription_plan_url(@newspaper.id, sp.id), method: :delete %>
  <% end %>
  <br>
  <br>
<% end %>

<% if @newspaper.user == @current_user %>
  <%= button_to "Edit newspaper", newspaper_url(@newspaper), method: :edit %>
  <%= button_to "Delete newspaper", newspaper_url(@newspaper), method: :delete %>
  <%= link_to "Add subscription plan", new_newspaper_subscription_plan_url(@newspaper.id)  %>
<% end %>

app/views/subscription_plans/edit.html.erb
<h1>New Subscription Plan for <%= @np.title %></h1>

<form action="<%= newspaper_subscription_plan_url(@np.id, @subscription_plan.id) %>" method="post">
  <label for="subscription_plan_price">Price</label>
    <input type="text" placeholder="0.00" name="subscription_plan[price]" id="subscription_plan_price" value="<%= @subscription_plan.price %>">
    <br>
    Type:
    <br>
    <input type="checkbox" name="subscription_plan[is_weekly]" value="<%= true %>" id="subscription_weekly">
    <label for="subscription_weekly">Weekly</label>
    <input type="checkbox" name="subscription_plan[is_weekly]" value="<%= false %>" id="subscription_daily">
    <label for="subscription_daily">Daily</label>
    <br>

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="put">

    <input type="submit" name="Update">
</form>

app/views/subscription_plans/new.html.erb
<h1>New Subscription Plan</h1>

<form action="<%= newspaper_subscription_plans_url %>" method="post">
  <label for="subscription_plan_price">Price</label>
    <input type="text" placeholder="0.00" name="subscription_plan[price]" id="subscription_plan_price" value="<%= @subscription_plan.price %>">
    <br>
    Type:
    <br>
    <input type="checkbox" name="subscription_plan[is_weekly]" value="<%= true %>" id="subscription_weekly">
    <label for="subscription_weekly">Weekly</label>
    <input type="checkbox" name="subscription_plan[is_weekly]" value="<%= false %>" id="subscription_daily">
    <label for="subscription_daily">Daily</label>
    <br>

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" name="Create">
</form>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<form action="<%= users_url %>" method="post">
  <label for="user_name">Name</label>
  <input type="text" name="user[name]" id="user_name" value="<%= @user.name %>">
  <br>
  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>
  <label for="user_password_confirmation">Password confirmation</label>
  <input type="password" name="user[password_confirmation]" id="user_password_confirmation">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="put">

  <input type="submit" value="Update">
</form>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <!-- Add subscription info here? -->
    <li><%= user.name %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <label for="user_name">Name</label>
  <input type="text" name="user[name]" id="user_name" value="<%= @user.name %>">
  <br>
  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>
  <label for="user_password_confirmation">Password confirmation</label>
  <input type="password" name="user[password_confirmation]" id="user_password_confirmation">
  <br>
  <br>
  Subscriptions:
  <br>
  <br>
  <% @newspapers.each do |np| %>
    <label for="<%= np.title %>_subscription_plan"><%= np.title %></label>
    <br>
    <select name="user[subscription_plan_ids][]" id="<%= np.title %>_subscription_plan">
      <% np.subscription_plans.each do |sp| %>
        <option value="<%= sp.id %>"><%= sp.price %>, <%= sp.is_weekly ? "Weekly" : "Daily" %></option>
      <% end %>
    </select>
    <input type="hidden" name="user[subscription_plan_ids][]" value="">
    <br>
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <br>
  <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Subscriptions: </h3>
<ul>
  <% @user.subscription_plans.each do |sp| %>
    <li><%= "#{sp.newspaper.title}, $#{sp.price}, #{sp.is_weekly ? 'Weekly' : 'Daily'}" %></li>
  <% end %>
</ul>